contact/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contato/', include('contact_list.urls'), name="contact")
]

contact_list/urls.py
from django.urls import path
from .views import register, index, edit, delete

urlpatterns = [
    path(r'register', register, name="register"),
    path(r'index', index, name="index"),
    path(r'edit/<int:pk>', edit, name="edit"),
    path(r'delete/<int:pk>', delete, name="delete"),
]

contact_list/models.py
from django.db import models
from django.contrib.auth.models import User


class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nome')
    phone = models.CharField(max_length=9, verbose_name='Telefone')
    email = models.EmailField(verbose_name='Email')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

contact_list/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'user']

contact_list/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact
from .forms import ContactForm
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse

def register(request):
    form = ContactForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('index')
    return render(request, 'edit_create.html', {'form':form})

def index(request):
    contato = Contact.objects.all()
    context = {'contatos':contato}
    return render(request, 'index.html', context)

def edit(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ContactForm(instance=contact)
    return render(request, 'edit_create.html', {'form':form})

def delete(request, pk):
    contact = Contact.objects.get(pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('index')
    return render(request, 'delete.html', {'contact':contact})
    

contact_list/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Contact List - Projeto Final</title>

    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap4.min.css">


    <link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
</head>

<body>

    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">
                <span class="oi oi-list"></span> CONTACT LIST</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span class="oi oi-account-logout"></span> Sign up</a>
                    </li>
                </ul>
            </div>


        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy; Imersão 2018 - Fábrica de Software</span>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap4.min.js"></script>

    <script>
      $(document).ready(function () {
        $('#table-contact').DataTable({
          responsive: {
            details: {
              display: $.fn.dataTable.Responsive.display.modal({
                header: function (row) {
                  var data = row.data();
                  return 'Details for ' + data[0] + ' ' + data[1];
                }
              }),
              renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                tableClass: 'table'
              })
            }
          }
        });
      });
    </script>

</body>

</html>

contact_list/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja remover o contato?</p>
    <button class="btn btn-lg btn-primary btn-block" type="submit">SIM</button>
</form>
{% endblock %}

contact_list/templates/edit_create.html
{% extends 'base.html' %}
{% load staticfiles %}
    {% block content %}
        <div class="mt-5">
            <p>
                <a class="btn btn-lg btn-secondary" href="{% url 'index' %}" role="button">
                    <span class="oi oi-media-step-backward"></span> VOLTAR</a>
            </p>
        </div>

        <hr>
        <div class="mt-5">
            <form method="post" action="">{% csrf_token %}
                <div class="row">
                  <!--   <div class="col-md-6 mb-3">
                        <label for="id_name">Name</label>
                        {{form.name.label}}
                        {{form.name}}
                        <input type="text" class="form-control" id="id_name" placeholder="" value="" required>
                    </div>
                    <div class="col-md-6 mb-3"></div>
                    <div class="col-md-6 mb-3">
                        <label for="id_phone">Phone</label>
                        <input type="tel" class="form-control" id="id_phone" placeholder="">
                    </div>
                    <div class="col-md-6 mb-3"></div>
                    <div class="col-md-6 mb-3">
                        <label for="id_email">Email</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">@</span>
                            </div>
                            <input type="email" class="form-control" id="id_email" placeholder="you@example.com" required>
                            <div class="invalid-feedback" style="width: 100%;">
                                Your username is required.
                            </div>
                        </div> -->
                    {{form.as_p}}
                    </div>
                    <div class="col-md-6 mb-3"></div>

                </div>

                <div class="mt-5">
                    <p>
                        <button class="btn btn-lg btn-primary" type='submit' >
                            <span class="oi oi-check"></span> SUBMIT</a></button>
                    </p>
                </div>
            </form>
        </div>
    {% endblock %}

contact_list/templates/index.html
{% extends 'base.html' %}

  <!-- Begin page content -->
  {% block content %}

    <div class="mt-5">
      <p>
        <a class="btn btn-lg btn-primary" href="{% url 'register' %}" role="button"><span class="oi oi-plus"></span> NEW CONTACT</a>
      </p>
    </div>

    <hr>

    <div class="mt-5">
    <table id="table-contact" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Phone</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for contato in contatos %}
        <tr>
          <th scope="row">{{contato.id}}</th>
          <td>{{contato.name}}</td>
          <td>{{contato.phone}}</td>
          <td>{{contato.email}}</td>
          <td>
            <a class="btn btn-sm btn-warning" href="{% url 'edit' pk=contato.pk %}" role="button"><span class="oi oi-pencil"></span></a>
            <a class="btn btn-sm btn-danger" href="{% url 'delete' pk=contato.pk %}" role="button"><span class="oi oi-trash"></span></a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock %}

contact_list/templates/login.html
{% extends 'base.html' %}

{% block content %}

  <form method="post" class="form-signin" action="index.html">
    <div class="text-center mb-4">
      <img class="mb-4" src="../static/img/list_contact.png" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Log in to Contact List</h1>
    </div>

    <div class="form-label-group">
      <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
      <label for="id_username">Username</label>
    </div>

    <div class="form-label-group">
      <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
      <label for="id_password">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Imersão 2018 - Fábrica de Software</p>
  </form>
{% endblock %}